### PR TITLE
issue-7: added the MAINTAINERS file

### PR DESCRIPTION
**Pull request by harry251**
@t-fine Could you review it?

### CODE REVIEW

**Review by joewxboy — APPROVED** [review]
Looks good, thanks.

**Comment by joewxboy** [comment]
@playground Should you be a maintainer on this repo?

**Review by johnwalicki — CHANGES_REQUESTED** [review]
I think Jeff Lu should also be a maintainer.

**Comment by harry251** [comment]
Can I get Jeff Lu's email? I am guessing Jeff's git is playground.

**Pull request merged**
